#!/usr/bin/env bash
# Mindbeamer CustomPiOS Module Install Script
# Script to install mindbeamer dependencies on CustomPiOS.
# Written by Jason Spriggs
# GPL V3
########

# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
unpack /filesystem/etc /etc
unpack /filesystem/boot /boot
unpack /filesystem/opt /opt
unpack /filesystem/var/www/html /var/www/html

echo "disable_overscan=1" >> /boot/config.txt
apt-get update -y
#apt full-upgrade -y
chown pi:pi /opt/mindbeamer
chmod 544 /opt/mindbeamer/signer.kbx
chmod +x /etc/network/if-up.d/mindbeamer
chown pi:pi /opt/greengrass
adduser --system ggc_user
addgroup --system ggc_group
apt autoremove
apt-get install -y gcc g++ make ntfs-3g unclutter openjdk-8-jdk usbmount chrony netcat
echo "unclutter -idle 0.01 -root" >> /etc/X11/xinit/xinitrc
sed -i 's/PrivateMounts=yes/PrivateMounts=no/g' /usr/lib/systemd/system/systemd-udevd.service
curl -sSL https://deb.nodesource.com/setup_14.x | bash -
apt-get install -y nodejs
apt autoremove
apt-get clean
npm install -g pnpm

# Unpack root at the end, so files are modified before
#unpack /filesystem/root /
