#!/bin/sh

FLAGFILE=/var/run/mindbeamer-network

case "$IFACE" in
    lo)
        # The loopback interface does not count.
        # only run when some other interface comes up
        exit 0
        ;;
    *)
        ;;
esac

if [ -e $FLAGFILE ]; then
    exit 0
else
    sleep 30
    /bin/bash /opt/mindbeamer/provision.sh
    touch $FLAGFILE
fi
